FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG VITE_APP_BASE_URL
ENV VITE_APP_BASE_URL=$VITE_APP_BASE_URL
ARG VITE_APP_TEST_USER_ID
ENV VITE_APP_TEST_USER_ID=$VITE_APP_TEST_USER_ID
ARG VITE_APP_TEST_INSTRUCTOR_ID
ENV VITE_APP_TEST_INSTRUCTOR_ID=$VITE_APP_TEST_INSTRUCTOR_ID

RUN npm run build


FROM caddy:2-alpine

COPY --from=build /app/dist /usr/share/caddy
